# Use rocker for R and tidyverse support
FROM rocker/tidyverse:latest

# Install system dependencies (if needed)
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    && apt-get clean

# Set working directory
WORKDIR C:\Users\Utente\Desktop\magistrale\programming\exam\molecular

# Copy your package and analysis script into the container
COPY molecular .

# Install your R package (assumes it's local)
RUN R CMD INSTALL molecular.

# Run the analysis when the container starts
CMD ["Rscript", "run_analysis.R"]
